config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#index'

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_up: 'signup' }
  get 'logout', to: 'pages#logout', as: 'logout'
  get 'lp', to: 'pages#lp', as: 'lp'

  resources :subscribe, only: [:index]
  resources :dashboard, only: [:index]
  resources :account, only: [:index, :update]
  resources :billing_portal, only: [:create]
  match '/billing_portal' => 'billing_portal#create', via: [:get]
  match '/cancel' => 'billing_portal#destroy', via: [:get]


  resources :nutrition_profiles
  resources :addresses
  resources :orders
  post '/change_meal', to: 'orders#change_meal', as: 'change_meal'
  

  # static pages
  pages = %w(
    privacy terms
  )

  pages.each do |page|
    get "/#{page}", to: "pages##{page}", as: "#{page.gsub('-', '_')}"
  end

  # admin panels
  authenticated :user, -> user { user.admin? } do
    namespace :admin do
      resources :dashboard, only: [:index]
      resources :impersonations, only: [:new]
      resources :users, only: [:edit, :update, :destroy]
    end

    # convenience helper
    get 'admin', to: 'admin/dashboard#index'
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all.order(created_at: :desc)
    @pending_orders = Order.where(status: 'pending').all
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  before_action :set_flashes

  def index
    @pending_order = current_user.orders.where(status: 'pending').first
    @past_orders = current_user.orders.where(status: 'delivered')
    @nutrition_profile = current_user.nutrition_profile
    @address = current_user.address
  end

  private

  def set_flashes
    if params[:subscribed] == 'true'
      current_user.delay.set_stripe_subscription
      flash.now[:notice] = 'Your account is now active!'
    end
  end
end

app/views/dashboard/index.html.erb
<!-- Heading -->
<%= render partial: "shared/heading", locals: { title: 'Dashboard', description: '' } %>

<div class="space-y-12 py-12 xl:space-y-15">


<!-- Meal of the Day -->

<div>
  <div class="mt-5 bg-white shadow sm:rounded-lg">
    <div class="px-4 py-5 sm:p-6">
      <% if @pending_order.present? %>
        <h2 class="text-base font-semibold leading-6 text-black"><%= @pending_order.dish_name %></h2>
        <div class="mt-2 max-w-xl text-sm text-gray-500">
          <p class="mb-2"><%= @pending_order.dish_ingredients %></p>
          <p class="mb-2">Total calories: <%= @pending_order.total_calories %></p>
          <p > Delivered today at <%= @address.delivery_time %></p>
          
        </div>
        <div class="mt-5 inline-flex gap-2">
          <%= button_to "Change Meal", change_meal_path, method: :post, class: "inline-flex items-center rounded-md bg-sky-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-sky-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-sky-500" %>
          <%= button_to "Cancel Order", order_path(@pending_order), method: :delete, class: "inline-flex items-center rounded-md bg-red-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-red-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-sky-500" %>
        </div>
      <% else %>
          <p>You don’t have an order yet.</p>
          <%= button_to "Create New Order", orders_path, method: :post, params: { user_id: current_user.id }, class: "inline-flex items-center rounded-md bg-sky-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-sky-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-sky-500" %>
      <% end %>
    </div>
  </div>
</div>


<!-- Top Stats -->
<div>
  <dl class="mt-5 grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3">
    <div class="relative overflow-hidden rounded-lg bg-white px-4 pb-12 pt-5 shadow sm:px-6 sm:pt-6">
      <dt>
        <div class="absolute rounded-md bg-sky-500 p-3">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 text-white">
            <path stroke-linecap="round" stroke-linejoin="round" d="M10.5 6a7.5 7.5 0 107.5 7.5h-7.5V6z" />
            <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 10.5H21A7.5 7.5 0 0013.5 3v7.5z" />
          </svg>

        </div>
        <p class="ml-16 truncate text-sm font-medium text-gray-500">Daily Calorie Need</p>
      </dt>
      <dd class="ml-16 flex items-baseline pb-6 sm:pb-7">
        <p class="text-1xl font-semibold text-gray-900"><%= @nutrition_profile.daily_calorie_need %></p>
        <p class="ml-2 flex items-baseline text-sm font-semibold text-gray-400">
          kcal
        </p>
        <div class="absolute inset-x-0 bottom-0 bg-gray-50 px-4 py-4 sm:px-6">
          <div class="text-sm">
            <%= link_to current_user.nutrition_profile, class: "font-medium text-sky-600 hover:text-sky-500" do %>
              Update
            <% end %>
          </div>
        </div>
      </dd>
    </div>
    <div class="relative overflow-hidden rounded-lg bg-white px-4 pb-12 pt-5 shadow sm:px-6 sm:pt-6">
      <dt>
        <div class="absolute rounded-md bg-sky-500 p-3">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="h-6 w-6 text-white">
            <path stroke-linecap="round" stroke-linejoin="round" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z" />
          </svg>
        </div>
        <p class="ml-16 truncate text-sm font-medium text-gray-500">Health Goal</p>
      </dt>
      <dd class="ml-16 flex items-baseline pb-6 sm:pb-7">
        <p class="text-1xl font-semibold text-gray-900"><%= @nutrition_profile.health_goal %></p>
        <div class="absolute inset-x-0 bottom-0 bg-gray-50 px-4 py-4 sm:px-6">
          <div class="text-sm">
            <%= link_to current_user.nutrition_profile, class: "font-medium text-sky-600 hover:text-sky-500" do %>
              Update
            <% end %>
            </div>
        </div>
      </dd>
    </div>
    <div class="relative overflow-hidden rounded-lg bg-white px-4 pb-12 pt-5 shadow sm:px-6 sm:pt-6">
      <dt>
        <div class="absolute rounded-md bg-sky-500 p-3">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 text-white">
            <path stroke-linecap="round" stroke-linejoin="round" d="M8.25 18.75a1.5 1.5 0 01-3 0m3 0a1.5 1.5 0 00-3 0m3 0h6m-9 0H3.375a1.125 1.125 0 01-1.125-1.125V14.25m17.25 4.5a1.5 1.5 0 01-3 0m3 0a1.5 1.5 0 00-3 0m3 0h1.125c.621 0 1.129-.504 1.09-1.124a17.902 17.902 0 00-3.213-9.193 2.056 2.056 0 00-1.58-.86H14.25M16.5 18.75h-2.25m0-11.177v-.958c0-.568-.422-1.048-.987-1.106a48.554 48.554 0 00-10.026 0 1.106 1.106 0 00-.987 1.106v7.635m12-6.677v6.677m0 4.5v-4.5m0 0h-12" />
          </svg>
        </div>
        <p class="ml-16 truncate text-sm font-medium text-gray-500">Delivery Address</p>
      </dt>
      <dd class="ml-16 flex items-baseline pb-6 sm:pb-7">
        <p class="text-1xl font-semibold text-gray-900"><%= @address.street %>, <%= @address.city %></p>
        <div class="absolute inset-x-0 bottom-0 bg-gray-50 px-4 py-4 sm:px-6">
          <div class="text-sm">
            <%= link_to current_user.address, class: "font-medium text-sky-600 hover:text-sky-500" do %>
              Update
            <% end %>
          </div>
        </div>
      </dd>
    </div>
  </dl>
</div>

<!-- Recent activity table -->
<div class="px-4 sm:px-6 lg:px-8">
  <div class="sm:flex sm:items-center">
    <div class="sm:flex-auto">
      <h2 class="text-base font-semibold leading-6 text-gray-900">Your Recent Orders</h2>
    </div>
  </div>
  <div class="mt-8 flow-root">
    <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
        <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 sm:rounded-lg">
          <table class="min-w-full divide-y divide-gray-300">
            <thead class="bg-gray-50">
              <tr>
                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Meal</th>
                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Calories</th>
                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Status</th>
                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900"></th>
              </tr>
            </thead>
            <tbody class="divide-y divide-gray-200 bg-white">
              <% @past_orders.first(10).each do |order| %>
                <tr>
                  <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= order.dish_name %></td>
                  <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= order.total_calories %></td>
                  <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= order.status %></td>
                  <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500 text-right">
                    <% unless order.user_rating? %> 
                      <%= link_to 'Give Feedback', edit_order_path(order), class: "font-medium text-sky-600 hover:text-sky-500" %>
                    <% else %>
                      <%= link_to 'View', edit_order_path(order), class: "font-medium text-sky-600 hover:text-sky-500" %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <div class="mt-3 text-right">
  <%= link_to orders_path, class: "font-medium text-sky-600 hover:text-sky-500" do %>
    See all
  <% end %>
  </div>
</div>