config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#index'

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_up: 'signup' }
  get 'logout', to: 'pages#logout', as: 'logout'
  get 'lp', to: 'pages#lp', as: 'lp'

  resources :subscribe, only: [:index]
  resources :dashboard, only: [:index]
  resources :account, only: [:index, :update]
  resources :billing_portal, only: [:create]
  match '/billing_portal' => 'billing_portal#create', via: [:get]
  match '/cancel' => 'billing_portal#destroy', via: [:get]


  resources :nutrition_profiles
  resources :addresses
  resources :orders
  post '/change_meal', to: 'orders#change_meal', as: 'change_meal'
  

  # static pages
  pages = %w(
    privacy terms
  )

  pages.each do |page|
    get "/#{page}", to: "pages##{page}", as: "#{page.gsub('-', '_')}"
  end

  # admin panels
  authenticated :user, -> user { user.admin? } do
    namespace :admin do
      resources :dashboard, only: [:index]
      resources :impersonations, only: [:new]
      resources :users, only: [:edit, :update, :destroy]
    end

    # convenience helper
    get 'admin', to: 'admin/dashboard#index'
  end
end

app/views/shared/_flash.html.erb
<% visibility = 'hidden' unless (flash[:alert].present? || flash[:notice].present?) %>


<div class="<%= visibility %> md:grid md:grid-cols-3 md:gap-6 mb-6">  <%# TODO: Fix DOM breaking point 1024x850 %>
  <div class="md:col-span-1"></div>
  <div class="md:col-span-1">
    <% if flash[:alert].present? %>
      <div class="bg-red-100 border border-red-400 rounded-md text-red-700 px-4 py-3 rounded relative" role="alert">
        <strong class="font-bold">Uh oh!</strong>
        <span class="block sm:inline"><%= alert %></span>
        <span id="flash_alert_close" class="absolute top-0 bottom-0 right-0 px-4 py-3">
          <svg class="fill-current h-6 w-6 text-red-500" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
        </span>
      </div>
    <% end %>

    <% if flash[:notice].present? %>
    <div class="bg-lightgreen-100 border border-green-400 rounded-md text-green-700 px-4 py-3 rounded relative" role="alert">
      <strong class="font-bold">Cool!</strong>
      <span class="block sm:inline"><%= notice %></span>
      <span id="flash_alert_close" class="absolute top-0 bottom-0 right-0 px-4 py-3">
        <svg class="fill-current h-6 w-6 text-green-500" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
      </span>
    </div>
    <% end %>
  </div>
</div>

<!-- Flash management -->
<script type="text/javascript">
  var flashAlert = document.getElementById('flash_alert_close');
  if (flashAlert !== null) {
    document.getElementById('flash_alert_close').addEventListener('click', function() {
      this.parentElement.remove();
    });
  }
</script>

app/views/shared/_header.html.erb
<header class="py-6 px-6" data-controller="header">
  <nav class="flex items-center justify-between flex-wrap">
    <div class="flex items-center flex-no-shrink text-white mr-6">
      <% logo_path = current_user ? dashboard_index_path : root_path %>
      <%#= link_to logo_path do %>
        <%#= image_tag "logo_short.png",  style: "max-height: 42px" %>
      <%# end %>
      <span class="font-semibold text-xl tracking-tight"><%= ENV['COMPANY_NAME'] %></span>
    </div>
    <div class="block sm:hidden">
      <button class="navbar-burger flex items-center px-3 py-2 border rounded text-white border-white hover:text-white hover:border-white" data-action="click->header#toggleMobileNav">
        <svg class="text-black fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
          <title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/>
        </svg>
      </button>
    </div>

    <div id="main-nav" class="w-full flex-grow sm:flex text-right sm:w-auto hidden" data-header-target="mainNav">
      <div class="text-sm sm:flex-grow">
        <% if current_user %>
          <%= link_to 'Admin', admin_dashboard_index_path, class: nav_link_classes('admin/dashboard') if current_user.admin? %>
          <%= link_to 'Dashboard', dashboard_index_path, class: nav_link_classes('dashboard') %>
          <%= link_to 'Account', account_index_path, class: nav_link_classes('account') %>
          <%= link_to 'Logout', logout_path, class: nav_link_classes %>
        <% else %>
          <%# <%= link_to 'Contact', "mailto:#{ENV['ADMIN_EMAIL']}", target: '_blank', class: nav_link_classes('contact') %>
          <%= link_to 'Login', new_user_session_path, class: nav_link_classes('login') %>
          <%= link_to 'Signup', new_user_registration_path, class: 'ml-8 whitespace-nowrap text-base font-medium inline-flex items-center justify-center px-4 py-2 border border-transparent rounded-md shadow-sm text-white bg-sky-600 hover:bg-sky-700' %>
        <% end %>
      </div>
    </div>
  </nav>
</header>


<!-- smooth scroll nav links -->
<script type="text/javascript">
  document.querySelectorAll('a[href^="#"]').forEach(anchor => {
      anchor.addEventListener('click', function (e) {
          e.preventDefault();

          document.querySelector(this.getAttribute('href')).scrollIntoView({
              behavior: 'smooth'
          });
      });
  });
</script>

app/views/shared/_heading.html.erb
<% description ||= '' %>
<div class="text-center mb-4">
  <h1 class="mt-1 font-extrabold text-gray-900 text-4xl sm:text-4xl sm:tracking-tight lg:text-5xl"><%= title %></h1>
  <p class="max-w-xl mt-5 mx-auto text-xl text-gray-500"><%= description.html_safe %></p>
</div>

app/views/shared/_script_tags.html.erb
<script type="text/javascript">
  document.querySelectorAll('a[href^="#"]').forEach(anchor => {
      anchor.addEventListener('click', function (e) {
          e.preventDefault();

          document.querySelector(this.getAttribute('href')).scrollIntoView({
              behavior: 'smooth'
          });
      });
  });
</script>

app/views/shared/_shell.html.erb
<div>
  <div id="backdrop" class="relative z-50 lg:hidden" role="dialog" aria-modal="true">
    <div class="fixed inset-0 bg-gray-900/80"></div>

    <div class="fixed inset-0 flex">
      <div class="relative mr-16 flex w-full max-w-xs flex-1">
        <div class="absolute left-full top-0 flex w-16 justify-center pt-5">
          <button type="button" id="close-sidebar-button" class="-m-2.5 p-2.5">
            <span class="sr-only">Close sidebar</span>
            <svg class="h-6 w-6 text-white" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        <div id="sidebar" class="flex grow flex-col gap-y-5 overflow-y-auto bg-gray-900 px-6 pb-2 ring-1 ring-white/10">
          <div class="flex h-16 shrink-0 items-center">
            <%= image_tag('logo_short.png', alt: 'Your Company', class: 'h-8 w-auto') %>
          </div>
          <nav class="flex flex-1 flex-col">
            <ul role="list" class="flex flex-1 flex-col gap-y-7">
              <li>
                <ul role="list" class="-mx-2 space-y-1">
                  <li>
                    <a href="/dashboard" class="text-gray-400 hover:text-white hover:bg-gray-800 group flex gap-x-3 rounded-md p-2 text-sm leading-6 font-semibold">
                      <svg class="h-6 w-6 shrink-0" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 12l8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25" />
                      </svg>
                      Dashboard
                    </a>
                  </li>
                  <li>
                    <%= link_to current_user.nutrition_profile, class: "text-gray-400 hover:text-white hover:bg-gray-800 group flex gap-x-3 rounded-md p-2 text-sm leading-6 font-semibold" do %>
                    <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6 shrink-0" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor"  aria-hidden="true">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M15 9h3.75M15 12h3.75M15 15h3.75M4.5 19.5h15a2.25 2.25 0 002.25-2.25V6.75A2.25 2.25 0 0019.5 4.5h-15a2.25 2.25 0 00-2.25 2.25v10.5A2.25 2.25 0 004.5 19.5zm6-10.125a1.875 1.875 0 11-3.75 0 1.875 1.875 0 013.75 0zm1.294 6.336a6.721 6.721 0 01-3.17.789 6.721 6.721 0 01-3.168-.789 3.376 3.376 0 016.338 0z" />
                    </svg>
                    Nutrition Profile
                    <% end %>
                  </li>
                  <li>
                    <%= link_to current_user.address, class: "text-gray-400 hover:text-white hover:bg-gray-800 group flex gap-x-3 rounded-md p-2 text-sm leading-6 font-semibold" do %>
                    <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6 shrink-0" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M8.25 18.75a1.5 1.5 0 01-3 0m3 0a1.5 1.5 0 00-3 0m3 0h6m-9 0H3.375a1.125 1.125 0 01-1.125-1.125V14.25m17.25 4.5a1.5 1.5 0 01-3 0m3 0a1.5 1.5 0 00-3 0m3 0h1.125c.621 0 1.129-.504 1.09-1.124a17.902 17.902 0 00-3.213-9.193 2.056 2.056 0 00-1.58-.86H14.25M16.5 18.75h-2.25m0-11.177v-.958c0-.568-.422-1.048-.987-1.106a48.554 48.554 0 00-10.026 0 1.106 1.106 0 00-.987 1.106v7.635m12-6.677v6.677m0 4.5v-4.5m0 0h-12" />
                    </svg>
                      Delivery Settings
                    <% end %>
                  </li>
                </ul>
              </li>
              <li class="absolute-bottom mt-auto">
                <%= link_to 'Admin', admin_dashboard_index_path, class: "text-gray-400 hover:text-white hover:bg-gray-800 group flex gap-x-3 rounded-md p-2 text-sm leading-6 font-semibold" if current_user.admin? %>
              </li>
              <li class="absolute-bottom mb-10">
                <a href="/logout" class="text-gray-400 hover:text-white hover:bg-gray-800 group flex gap-x-3 rounded-md p-2 text-sm leading-6 font-semibold">
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 9V5.25A2.25 2.25 0 0013.5 3h-6a2.25 2.25 0 00-2.25 2.25v13.5A2.25 2.25 0 007.5 21h6a2.25 2.25 0 002.25-2.25V15M12 9l-3 3m0 0l3 3m-3-3h12.75" />
                  </svg>
                  Logout
                </a>
              </li>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </div>

  <!-- Static sidebar for desktop -->
  <div class="hidden lg:fixed lg:inset-y-0 lg:z-50 lg:flex lg:w-72 lg:flex-col">
    <div class="flex grow flex-col gap-y-5 overflow-y-auto bg-gray-900 px-6">
      <div class="flex h-16 shrink-0 items-center">
        <%= image_tag('logo_short.png', alt: 'Your Company', class: 'h-8 w-auto') %>
      </div>
      <nav class="flex flex-1 flex-col">
        <ul role="list" class="flex flex-1 flex-col gap-y-7">
          <li>
            <ul role="list" class="-mx-2 space-y-1">
              <li>
                <a href="/dashboard" class="text-gray-400 hover:text-white hover:bg-gray-800 group flex gap-x-3 rounded-md p-2 text-sm leading-6 font-semibold">
                  <svg class="h-6 w-6 shrink-0" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 12l8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25" />
                  </svg>
                  Dashboard
                </a>
              </li>
              <li>
                <%= link_to current_user.nutrition_profile, class: "text-gray-400 hover:text-white hover:bg-gray-800 group flex gap-x-3 rounded-md p-2 text-sm leading-6 font-semibold" do %>
                <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6 shrink-0" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" >
                    <path stroke-linecap="round" stroke-linejoin="round" d="M15 9h3.75M15 12h3.75M15 15h3.75M4.5 19.5h15a2.25 2.25 0 002.25-2.25V6.75A2.25 2.25 0 0019.5 4.5h-15a2.25 2.25 0 00-2.25 2.25v10.5A2.25 2.25 0 004.5 19.5zm6-10.125a1.875 1.875 0 11-3.75 0 1.875 1.875 0 013.75 0zm1.294 6.336a6.721 6.721 0 01-3.17.789 6.721 6.721 0 01-3.168-.789 3.376 3.376 0 016.338 0z" />
                </svg>
                Nutrition Profile
                <% end %>
              </li>
              <li>
                <%= link_to current_user.address, class: "text-gray-400 hover:text-white hover:bg-gray-800 group flex gap-x-3 rounded-md p-2 text-sm leading-6 font-semibold" do %>
                <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6 shrink-0" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" >
                    <path stroke-linecap="round" stroke-linejoin="round" d="M8.25 18.75a1.5 1.5 0 01-3 0m3 0a1.5 1.5 0 00-3 0m3 0h6m-9 0H3.375a1.125 1.125 0 01-1.125-1.125V14.25m17.25 4.5a1.5 1.5 0 01-3 0m3 0a1.5 1.5 0 00-3 0m3 0h1.125c.621 0 1.129-.504 1.09-1.124a17.902 17.902 0 00-3.213-9.193 2.056 2.056 0 00-1.58-.86H14.25M16.5 18.75h-2.25m0-11.177v-.958c0-.568-.422-1.048-.987-1.106a48.554 48.554 0 00-10.026 0 1.106 1.106 0 00-.987 1.106v7.635m12-6.677v6.677m0 4.5v-4.5m0 0h-12" />
                </svg>
                  Delivery Settings
                <% end %>
              </li>
            </ul>
          </li>
          <li class="absolute-bottom mt-auto">
            <%= link_to 'Admin', admin_dashboard_index_path, class: "text-gray-400 hover:text-white hover:bg-gray-800 group flex gap-x-3 rounded-md p-2 text-sm leading-6 font-semibold" if current_user.admin? %>
          </li>
          <li class="absolute-bottom mb-10">
            <a href="/logout" class="text-gray-400 hover:text-white hover:bg-gray-800 group flex gap-x-3 rounded-md p-2 text-sm leading-6 font-semibold">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 9V5.25A2.25 2.25 0 0013.5 3h-6a2.25 2.25 0 00-2.25 2.25v13.5A2.25 2.25 0 007.5 21h6a2.25 2.25 0 002.25-2.25V15M12 9l-3 3m0 0l3 3m-3-3h12.75" />
              </svg>
              Logout
            </a>
          </li>
        </ul>
      </nav>
    </div>
  </div>

  <div class="sticky top-0 z-40 flex items-center gap-x-6 bg-gray-900 px-4 py-4 shadow-sm sm:px-6 lg:hidden">
    <button id="open-sidebar-button" type="button" class="-m-2.5 p-2.5 text-gray-400 lg:hidden">
      <span class="sr-only">Open sidebar</span>
      <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
        <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
      </svg>
    </button>
  </div>

  <main class="py-10 lg:pl-72">
    <div class="px-4 sm:px-6 lg:px-8">
      <%= render "shared/flash" %>
      <%= yield %>
    </div>
  </main>
</div>

<script>
// Select the DOM element
const backdropEl = document.getElementById('backdrop');
const sidebarButtonOpen = document.getElementById('open-sidebar-button');
const sidebarButtonClose = document.getElementById('close-sidebar-button');
const sidebarEl = document.getElementById('sidebar');

// Event listeners
sidebarButtonOpen.addEventListener('click', function(){
  backdropEl.style.display = 'block'; // Display the backdrop
  sidebarEl.style.transform = 'translateX(0)'; // Show the sidebar
});

sidebarButtonClose.addEventListener('click', function(){
  sidebarEl.style.transform = 'translateX(-100%)'; // Hide the sidebar
  setTimeout(function() { backdropEl.style.display = 'none'; }, 300); // Hide the backdrop after the transition
});

// Initialization
function init() {
  sidebarEl.style.transition = 'transform 300ms ease-in-out'; // Add transition to sidebar
  sidebarEl.style.transform = 'translateX(-100%)'; // Initially hide the sidebar
  backdropEl.style.display = 'none'; // Initially hide the backdrop
}

init();

// mark current page in navigation
window.onload = function markCurrentPage() {
  const navLinks = document.querySelectorAll('nav ul li a');
  const currentPage = window.location.pathname;

  navLinks.forEach((link) => {
    // Remove selected state classes from all links
    link.classList.remove('bg-gray-800', 'text-white');
    // Add default state classes back to all links
    link.classList.add('text-gray-400', 'hover:text-white', 'hover:bg-gray-800');

    if (link.pathname === currentPage) {
      link.classList.remove('text-gray-400', 'hover:text-white', 'hover:bg-gray-800');
      link.classList.add('bg-gray-800', 'text-white');
    }
  });
};

markCurrentPage();
</script>