config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#index'

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_up: 'signup' }
  get 'logout', to: 'pages#logout', as: 'logout'
  get 'lp', to: 'pages#lp', as: 'lp'

  resources :subscribe, only: [:index]
  resources :dashboard, only: [:index]
  resources :account, only: [:index, :update]
  resources :billing_portal, only: [:create]
  match '/billing_portal' => 'billing_portal#create', via: [:get]
  match '/cancel' => 'billing_portal#destroy', via: [:get]


  resources :nutrition_profiles
  resources :addresses
  resources :orders
  post '/change_meal', to: 'orders#change_meal', as: 'change_meal'
  

  # static pages
  pages = %w(
    privacy terms
  )

  pages.each do |page|
    get "/#{page}", to: "pages##{page}", as: "#{page.gsub('-', '_')}"
  end

  # admin panels
  authenticated :user, -> user { user.admin? } do
    namespace :admin do
      resources :dashboard, only: [:index]
      resources :impersonations, only: [:new]
      resources :users, only: [:edit, :update, :destroy]
    end

    # convenience helper
    get 'admin', to: 'admin/dashboard#index'
  end
end

app/models/nutrition_profile.rb
class NutritionProfile < ApplicationRecord
  belongs_to :user

  ACTIVITY_LEVEL_MULTIPLIERS = {
    'Sedentary' => 1.2,
    'Moderately active' => 1.55,
    'Vigorously active' => 1.725,
    'Extremely active' => 1.9
  }.freeze
  
  SEX_BMR_FACTORS = {
    "Male" => { mul_weight: 13.75, mul_height: 5.003, factor: 66.5, mul_age: 6.75 },
    "Female" => { mul_weight: 9.563, mul_height: 1.850, factor: 655.1, mul_age: 4.676 }
  }.freeze
  
  validates :sex, :age, :height, :weight, :activity_level, :health_goal, presence: true
  before_save :set_daily_calorie_need

  def save_or_update
    current_user.nutrition_profile.nil? ? save : update
  end

  def calculate_daily_calorie_need
    (ACTIVITY_LEVEL_MULTIPLIERS.fetch(activity_level, "You have to fill out your nutrition profile first.") * calculate_bmr).to_i
  end

  def calculate_bmr 
    factors = SEX_BMR_FACTORS[sex]
    factors[:factor] + (factors[:mul_weight] * weight) + (factors[:mul_height] * height) - (factors[:mul_age] * age)
  end

  private

  def set_daily_calorie_need
    self.daily_calorie_need = calculate_daily_calorie_need
  end

end

app/controllers/nutrition_profiles_controller.rb
class NutritionProfilesController < ApplicationController
    before_action :authenticate_user!
    before_action :set_nutrition_profile
    
    def show
        @nutrition_profile = current_user.nutrition_profile
    end

    def new
        @nutrition_profile = current_user.nutrition_profile || current_user.build_nutrition_profile
    end

    def create
        @nutrition_profile = current_user.build_nutrition_profile(nutrition_profile_params)

        if current_user.nutrition_profile.nil?
            if @nutrition_profile.save
            redirect_to @nutrition_profile, notice: 'Nutrition profile was successfully created.'
            else
            render :new
            end
        else
            if @nutrition_profile.update(nutrition_profile_params)
            redirect_to @nutrition_profile, notice: 'Nutrition profile was successfully updated.'
            else
            render :edit, alert: 'Nutrition Profile could not be created. Try again.'
            end
        end
    end

    def update
        @nutrition_profile = current_user.nutrition_profile

        if @nutrition_profile.update(nutrition_profile_params)
          redirect_to @nutrition_profile, notice: 'Nutrition profile was successfully updated.'
        else
          render :edit,  alert: 'Nutrition Profile was not updated. Try again.'
        end
    end

    private

    def set_nutrition_profile
        @nutrition_profile = current_user.nutrition_profile
    end

    def nutrition_profile_params
        params.require(:nutrition_profile).permit(:sex, :age, :height, :weight, :activity_level, :health_goal, :daily_calorie_need)
    end
    
end
    

app/views/nutrition_profiles/_form.html.erb
<%= form_for @nutrition_profile do |form| %>
    <div class="space-y-12">
        <div class="sm:col-span-2">
            <label for="sex" class="block text-sm font-medium leading-6 text-gray-900">Sex</label>
            <%= form.select :sex, ['Female', 'Male'],
                {},
                { class: 'mt-2 block w-full rounded-md border-0 py-1.5 pl-3 pr-10 text-gray-900 
                ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-indigo-600 sm:text-sm sm:leading-6' } 
            %>
        </div>

        <div class="sm:col-span-3">
            <label for="age" class="block text-sm font-medium leading-6 text-gray-900">Age</label>
            <div class="mt-2">
                <%= form.number_field :age, id: 'age', class: 'block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6' %>
            </div>
        </div>

        <div class="col-span-full">
            <label for="height" class="block text-sm font-medium leading-6 text-gray-900">Height in cm</label>
            <div class="mt-2">
                <%= form.number_field :height, id: 'height', class: 'block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6' %>
            </div>
        </div>

        <div class="sm:col-span-2 sm:col-start-1">
            <label for="weight" class="block text-sm font-medium leading-6 text-gray-900">Weight in kg</label>
            <div class="mt-2">
                <%= form.number_field :weight, step: :any, id: 'weight', class: 'block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6' %>
            </div>
        </div>

        <div class="sm:col-span-2">
            <label for="activity_level" class="block text-sm font-medium leading-6 text-gray-900">Activity Level</label>
            <%= form.select :activity_level, 
                ['Sedentary', 'Moderately active', 'Vigorously active', 'Extremely active'],
                {},
                { class: 'mt-2 block w-full rounded-md border-0 py-1.5 pl-3 pr-10 text-gray-900 
                ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-indigo-600 sm:text-sm sm:leading-6' } 
            %>
        </div>

        <div class="sm:col-span-2">
            <label for="health_goal" class="block text-sm font-medium leading-6 text-gray-900">Health Goal</label>
            <%= form.select :health_goal, 
                ['Losing Weight', 'Gaining Muscle', 'Higher Productivity/Focus'],
                {},
                { class: 'mt-2 block w-full rounded-md border-0 py-1.5 pl-3 pr-10 text-gray-900 
                ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-indigo-600 sm:text-sm sm:leading-6' } 
            %>
        </div>

        <%= form.submit "Save", class: 'inline rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600' %>

    </div>

<% end %>

app/views/nutrition_profiles/_nutrition_profile.html.erb
<div class="overflow-hidden bg-white shadow sm:rounded-lg">
  <div class="border-t border-gray-100">
    <dl class="divide-y divide-gray-100">
      <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-900">Sex</dt>
        <dd class="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0"><%= @nutrition_profile.sex %></dd>
      </div>
      <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-900">Age</dt>
        <dd class="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0"><%= @nutrition_profile.age %></dd>
      </div>
      <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-900">Height</dt>
        <dd class="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0"><%= @nutrition_profile.height %> cm</dd>
      </div>
      <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-900">Weight</dt>
        <dd class="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0"><%= @nutrition_profile.weight %> kg</dd>
      </div>
      <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-900">Activity Level</dt>
        <dd class="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0"><%= @nutrition_profile.activity_level %></dd>
      </div>
      <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-900">Health Goal</dt>
        <dd class="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0"><%= @nutrition_profile.health_goal %></dd>
      </div>
    </dl>
  </div>
</div>

app/views/nutrition_profiles/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl pb-12">Nutrition Profile</h1>

  <%= render "form" %>

</div>

app/views/nutrition_profiles/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl pb-12">New Nutrition Profile</h1>

  <%= render "form" %>

</div>

app/views/nutrition_profiles/show.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl pb-12">Nutrition Profile</h1>

<% if @nutrition_profile.nil? %>
  <p>You have not set up a nutrition profile yet.</p>
<% else %>
  <%= render @nutrition_profile %>
<% end %>



<% if @nutrition_profile.nil? %>
    <%= link_to 'New Nutrition Profile', new_nutrition_profile_path, class: "mt-7 rounded-lg py-3 px-5 bg-sky-600 text-white inline-block font-medium" %>
<% else %>
    <%= link_to 'Edit Nutrition Profile', edit_nutrition_profile_path, class: "mt-7 rounded-lg py-3 px-5 bg-sky-600 text-white inline-block font-medium" %>
<% end %>


</div>